devices:  # list of devices
  - name: test-pylogix      # device name 
    frequency: 1            # minimum polling frequency device in seconds
    driver: pylogix         # driver type [pylogix/modbus/xxx]
    ip: '10.4.43.103'       # ip address for the device
    slot: 0                 # optional, 0 is default
    port: 44818             # optional, default as per protocl

    tags:
      - type: ping          # tag type [ping/counter/data]
        name: 'test-ping'   # name for data point
        tag: 'Program:MainProgram.ProdCount.ACC'  # PLC tag name
        frequency: 5        # optional, defaults to device freq
                            # highest freq value used if both specified

      - type: conter
        name: 'test-count'  # name for data point
        machine: 1530       # machine number for database entry
        scale: 1            # number of parts made per cycle
        tag: 'Program:MainProgram.ProdCount.ACC'  # PLC tag name

        # to get the part type, specify either:
        # a part_number_text tag
        part_number_text: 'Program:MainProgram.ProdCountpartText' 
        # or an index tag and the part_dict
        part_number_index: 'Program:MainProgram.ProdCountpartDINT'
        part_dict:
          0: '50-0455'
          1: '50-9341'

        frequency: 5        # optional, defaults to device freq

