TAG : 'Program:MainProgram.ProdCount.ACC'
PLC_IP : '10.4.43.103'

devices:
  - name: test-pylogix
    frequency: 1
    driver: pylogix
    ip: '10.4.43.103'
    slot: 0           # optional

    tags:
      - type: ping
        name: 'test-ping'
        tag: 'Program:MainProgram.ProdCount.ACC'
        frequency: 5 # optional

    counter_tag: 'Program:MainProgram.ProdCount.ACC'
    part_type_tag: 'Program:MainProgram.ProdCountPartText'


